# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sysm√§Summit2016
email: sysmasummit@gmail.com
description: "We build the Future." 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sysmasummit.com" # the base hostname & protocol for your site
twitter_username: sysmasummit
github_username:  sysmasummit

# Build settings
markdown: kramdown
